### ISSUE TITLE
Speedup by unrolling + computed goto for jeaiii when digits <= 8

### ISSUE THREAD

**Issue by chrooti** [jk-jeon/dtoa-benchmark#2]
Not really an issue, sorry for polluting the issue section but I couldn't find a way of contacting you and maybe you're interested in this :)

I stumbled upon your blog post and while copying/changing things I stumbled upon a (very minor but apparently consistent) performance improvement.

Basically I unrolled manually the case digits <= 8 and then used a computed goto to jump to the correct iteration. Nothing fancy, the ASM is _way bigger_ than yours but maybe this interests you anyway.

https://quick-bench.com/q/ZeZDP1NCi4zyy_YSDR0jjKhEVDY

And thanks for the detailed explanation in the blog post :) 

EDIT: only after I finished posting this I realize this is the dtoa repo and not the itoa one. Embarassing, sorry again.

**Comment by chrooti** [comment]
After a bunch more benchmarking it seems we're at the point where the difference is just noise, nvm.

**Comment by jk-jeon** [comment]
@chrooti  Hi, I didn't turn on the notification setting on this repo so I didn't know about this until now. I didn't even know that the issue board is turned on 😂

By the way, this repo exists solely for the purpose of keeping the benchmark code of the Dragonbox repo, and as you can see I'm not even the original author of it. (The original author, Milo Yip, seems to abandon it and don't respond at all to any issues and PR's at this point.)

If you have any cool ideas about the itoa stuffs, I recommend you to go directly to James Edward Anhalt III's itoa repo ([here](https://github.com/jeaiii/itoa)). He has read my post and responded with even further improvements.

Thanks for your input though! Glad you find my post interesting!
